import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Post from '../components/Post'
import HomeRightbar from '../components/HomeRightbar'
import { api } from '../urlConfig'

export const getStaticProps = async () => {
  const res = await fetch(`${api}/initial-data/1`)
  console.log(res)
  const data =await res.json()
  
  return {
    props:{posts:data.posts}
  }
  
}

export default function Home({posts}) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container">
        <div className={styles.homeMain}>
          <div className={styles.posts}>
            {posts.map((post,index) => (
              <Post key={index} post={post} />
            ))}

           
          </div>
          <div className={styles.homeRightBar}>
            <HomeRightbar />
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
